# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jcperson',
            old_name='resid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='jcbook',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jcbook',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='jcperson',
            name='name',
            field=models.CharField(max_length=31),
        ),
    ]
