# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0002_auto_20170209_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='jcbook',
            name='owner',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='使用人', to='testmodel.JCPerson'),
            preserve_default=False,
        ),
    ]
